export const FETCHING_PHOTOS = 'FETCHING_PHOTOS';
export const FETCHING_PHOTOS_SUCCESS = 'FETCHING_PHOTOS_SUCCESS';
export const FETCHING_PHOTOS_FAIL = 'FETCHING_PHOTOS_FAIL';

export const FETCHING_PHOTO = 'FETCHING_PHOTO';
export const FETCHING_PHOTO_SUCCESS = 'FETCHING_PHOTO_SUCCESS';
export const FETCHING_PHOTO_FAIL = 'FETCHING_PHOTO_FAIL';
